language: ruby
rvm:
- 2.2.2
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
- cp config/database.yml.travis config/database.yml
- RAILS_ENV=test rake db:migrate
- export DISPLAY=:99.0
- rails s -p3000
- sh -e /etc/init.d/xvfb start
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/2d6c2c3386add37bde9d
    on_success: change
    on_failure: always
    on_start: false
addons:
  code_climate:
    repo_token: 2de0629e807efad30c00506561ae6b6ac6c23d7d25c0ee7f7e13c4cd0df9b97c
  hosts:
    - 0.0.0.0:3000
before_install:
- openssl aes-256-cbc -K $encrypted_f1c2b93d10a2_key -iv $encrypted_f1c2b93d10a2_iv
  -in config/secrets.yml.enc -out config/secrets.yml -d
