language: ruby
rvm: 
  -  "2.2.2"

before_script:
  -  psql -c 'create database travis_ci_test;' -U postgres
  -  cp config/database.yml.travis config/database.yml
  -  RAILS_ENV=test rake db:migrate

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/2d6c2c3386add37bde9d
    on_success: change  
    on_failure: always  
    on_start: false     

